question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "Haggis is traditionally ate on Burns Night.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "The French word for 'glass' is 'glace'.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "There are 86400 seconds in a day.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "The pickled gherkin was first added to hamburgers because a US health law required all fast-food to include a source of Vitamin C.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "The sum of all the numbers on a roulette wheel is 666.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "Albert Einstein had trouble with mathematics when he was in school.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "A pencil #039 lead is typically made from graphite, not lead",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "The word 'news' originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "'Typewriter' is the longest word that can be typed using only the first row on a QWERTY keyboard.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
